backend:
  name: git-gateway
  # repo: https://github.com/nikahughes/nikahughes.com
  # branch: main
  # site_domain: www.nikahughes.com

local_backend: true

local_backend:
  # when using a custom proxy server port
  url: http://127.0.0.1:8082/api/v1
  # when accessing the local site from a host other than 'localhost' or '127.0.0.1'
  allowed_hosts: ['127.0.0.1']

media_folder: "static/uploads"
public_folder: "images/uploads"

collections:
  - name: "listing" # Used in routes, e.g., /admin/collections/blog
    label: "Listing" # Used in the UI
    folder: "listings" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}